### ISSUE TITLE
Build failure on Mac OS X

### ISSUE THREAD

**Issue by nowsprinting** [ioriayane/KanmusuMemory#43]
最新のコミットでビルドが落ちてました。Mac OS X固有の問題かどうか未調査。

    In file included from mainwindow.cpp:16:
    In file included from ./mainwindow.h:19:
    In file included from /Applications/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow:1:
    In file included from /Applications/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h:45:
    In file included from /Applications/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h:45:
    In file included from /Applications/Qt/5.3/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h:45:
    In file included from /Applications/Qt/5.3/clang_64/lib/QtCore.framework/Headers/qglobal.h:72:
    /Applications/Qt/5.3/clang_64/lib/QtCore.framework/Headers/qsystemdetection.h:196:12: fatal error: 'TargetConditionals.h' file not found
    #  include <TargetConditionals.h>

**Comment by ioriayane** [comment]
masterブランチですと手元のMacでビルドできてます。
　OS X 10.10.1
　Qt 5.3.1

**Comment by nowsprinting** [comment]
ビルドサーバはOS X 10.9でした。

これっぽいですね
http://stackoverflow.com/questions/25940368/qt5-target-conditionals-not-found

**Comment by ioriayane** [comment]
それが原因だとqmake の時点で下のようなエラーになると思います。
Project ERROR: Could not resolve SDK path for 'macosx10.8'
（自分もこの問題でました）

**Comment by nowsprinting** [comment]
qmakeでは何もエラー出てないですね。近々環境整理してリトライしてみます

**Comment by nowsprinting** [comment]
下記環境でビルドできました（上記リンク先の`QMAKE_MAC_SDK`指定は無しで）
OS X 10.9.5
Qt 5.4.1

エラーが出ていたのがQt 5.3.xなのですが、5.4インストールに伴ない削除してしまったので再現して調査できなくなってしまいました。
